#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Name
No description available.
.PARAMETER Description
No description available.
.PARAMETER ZeroDay
No description available.
.PARAMETER CreatedAt
No description available.
.PARAMETER UpdatedAt
No description available.
.PARAMETER Rules
No description available.
.PARAMETER Vulnerability
No description available.
.PARAMETER FindingsCount
Count of confirmed open findings against the rule's vulnerability. Scoped to the requesting user's business units and the organization's finding impact threshold.
.PARAMETER AffectedKbEntryIds
KB entry IDs covered by this rule that have confirmed open findings, scoped to the requesting user's business units.
.OUTPUTS

ActiveDefenseRuleDetails<PSCustomObject>
#>

function Initialize-ActiveDefenseRuleDetails {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${ZeroDay},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CreatedAt},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${UpdatedAt},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Rules},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Vulnerability},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${FindingsCount},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [Decimal[]]
        ${AffectedKbEntryIds}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => ActiveDefenseRuleDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $Description) {
            throw "invalid value for 'Description', 'Description' cannot be null."
        }

        if ($null -eq $ZeroDay) {
            throw "invalid value for 'ZeroDay', 'ZeroDay' cannot be null."
        }

        if ($null -eq $CreatedAt) {
            throw "invalid value for 'CreatedAt', 'CreatedAt' cannot be null."
        }

        if ($null -eq $UpdatedAt) {
            throw "invalid value for 'UpdatedAt', 'UpdatedAt' cannot be null."
        }

        if ($null -eq $Rules) {
            throw "invalid value for 'Rules', 'Rules' cannot be null."
        }

        if ($null -eq $FindingsCount) {
            throw "invalid value for 'FindingsCount', 'FindingsCount' cannot be null."
        }

        if ($null -eq $AffectedKbEntryIds) {
            throw "invalid value for 'AffectedKbEntryIds', 'AffectedKbEntryIds' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "name" = ${Name}
            "description" = ${Description}
            "zeroDay" = ${ZeroDay}
            "createdAt" = ${CreatedAt}
            "updatedAt" = ${UpdatedAt}
            "rules" = ${Rules}
            "vulnerability" = ${Vulnerability}
            "findingsCount" = ${FindingsCount}
            "affectedKbEntryIds" = ${AffectedKbEntryIds}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ActiveDefenseRuleDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to ActiveDefenseRuleDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ActiveDefenseRuleDetails<PSCustomObject>
#>
function ConvertFrom-JsonToActiveDefenseRuleDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => ActiveDefenseRuleDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ActiveDefenseRuleDetails
        $AllProperties = ("id", "name", "description", "zeroDay", "createdAt", "updatedAt", "rules", "vulnerability", "findingsCount", "affectedKbEntryIds")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) {
            throw "Error! JSON cannot be serialized due to the required property 'description' missing."
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "zeroDay"))) {
            throw "Error! JSON cannot be serialized due to the required property 'zeroDay' missing."
        } else {
            $ZeroDay = $JsonParameters.PSobject.Properties["zeroDay"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createdAt"))) {
            throw "Error! JSON cannot be serialized due to the required property 'createdAt' missing."
        } else {
            $CreatedAt = $JsonParameters.PSobject.Properties["createdAt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "updatedAt"))) {
            throw "Error! JSON cannot be serialized due to the required property 'updatedAt' missing."
        } else {
            $UpdatedAt = $JsonParameters.PSobject.Properties["updatedAt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rules"))) {
            throw "Error! JSON cannot be serialized due to the required property 'rules' missing."
        } else {
            $Rules = $JsonParameters.PSobject.Properties["rules"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "findingsCount"))) {
            throw "Error! JSON cannot be serialized due to the required property 'findingsCount' missing."
        } else {
            $FindingsCount = $JsonParameters.PSobject.Properties["findingsCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "affectedKbEntryIds"))) {
            throw "Error! JSON cannot be serialized due to the required property 'affectedKbEntryIds' missing."
        } else {
            $AffectedKbEntryIds = $JsonParameters.PSobject.Properties["affectedKbEntryIds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vulnerability"))) { #optional property not found
            $Vulnerability = $null
        } else {
            $Vulnerability = $JsonParameters.PSobject.Properties["vulnerability"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "name" = ${Name}
            "description" = ${Description}
            "zeroDay" = ${ZeroDay}
            "createdAt" = ${CreatedAt}
            "updatedAt" = ${UpdatedAt}
            "rules" = ${Rules}
            "vulnerability" = ${Vulnerability}
            "findingsCount" = ${FindingsCount}
            "affectedKbEntryIds" = ${AffectedKbEntryIds}
        }

        return $PSO
    }

}

