#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER AttackerId
No description available.
.PARAMETER Name
No description available.
.PARAMETER Aliases
No description available.
.PARAMETER Type
No description available.
.PARAMETER OriginCountryCode
No description available.
.PARAMETER LastReportedDate
No description available.
.PARAMETER VictimCountries
No description available.
.PARAMETER TargetIndustries
No description available.
.PARAMETER AffectedTrackedHuntsCount
No description available.
.PARAMETER AffectedOpenFindingsCount
No description available.
.PARAMETER IsAffected
Whether the user has confirmed open findings against vulnerabilities exploited by this adversary. Scoped to the requesting user's business units and the organization's finding impact threshold.
.PARAMETER AffectedKbEntryIds
KB entry IDs that drive the `isAffected` flag, scoped to the requesting user's business units.
.OUTPUTS

AdversaryIntel<PSCustomObject>
#>

function Initialize-AdversaryIntel {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${AttackerId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Aliases},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OriginCountryCode},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${LastReportedDate},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VictimCountries},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${TargetIndustries},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${AffectedTrackedHuntsCount},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${AffectedOpenFindingsCount},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${IsAffected},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [Decimal[]]
        ${AffectedKbEntryIds}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => AdversaryIntel' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $AttackerId) {
            throw "invalid value for 'AttackerId', 'AttackerId' cannot be null."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $Type) {
            throw "invalid value for 'Type', 'Type' cannot be null."
        }

        if ($null -eq $IsAffected) {
            throw "invalid value for 'IsAffected', 'IsAffected' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "attackerId" = ${AttackerId}
            "name" = ${Name}
            "aliases" = ${Aliases}
            "type" = ${Type}
            "originCountryCode" = ${OriginCountryCode}
            "lastReportedDate" = ${LastReportedDate}
            "victimCountries" = ${VictimCountries}
            "targetIndustries" = ${TargetIndustries}
            "affectedTrackedHuntsCount" = ${AffectedTrackedHuntsCount}
            "affectedOpenFindingsCount" = ${AffectedOpenFindingsCount}
            "isAffected" = ${IsAffected}
            "affectedKbEntryIds" = ${AffectedKbEntryIds}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AdversaryIntel<PSCustomObject>

.DESCRIPTION

Convert from JSON to AdversaryIntel<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AdversaryIntel<PSCustomObject>
#>
function ConvertFrom-JsonToAdversaryIntel {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => AdversaryIntel' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AdversaryIntel
        $AllProperties = ("attackerId", "name", "aliases", "type", "originCountryCode", "lastReportedDate", "victimCountries", "targetIndustries", "affectedTrackedHuntsCount", "affectedOpenFindingsCount", "isAffected", "affectedKbEntryIds")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'attackerId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "attackerId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'attackerId' missing."
        } else {
            $AttackerId = $JsonParameters.PSobject.Properties["attackerId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) {
            throw "Error! JSON cannot be serialized due to the required property 'type' missing."
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isAffected"))) {
            throw "Error! JSON cannot be serialized due to the required property 'isAffected' missing."
        } else {
            $IsAffected = $JsonParameters.PSobject.Properties["isAffected"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "aliases"))) { #optional property not found
            $Aliases = $null
        } else {
            $Aliases = $JsonParameters.PSobject.Properties["aliases"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "originCountryCode"))) { #optional property not found
            $OriginCountryCode = $null
        } else {
            $OriginCountryCode = $JsonParameters.PSobject.Properties["originCountryCode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lastReportedDate"))) { #optional property not found
            $LastReportedDate = $null
        } else {
            $LastReportedDate = $JsonParameters.PSobject.Properties["lastReportedDate"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "victimCountries"))) { #optional property not found
            $VictimCountries = $null
        } else {
            $VictimCountries = $JsonParameters.PSobject.Properties["victimCountries"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "targetIndustries"))) { #optional property not found
            $TargetIndustries = $null
        } else {
            $TargetIndustries = $JsonParameters.PSobject.Properties["targetIndustries"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "affectedTrackedHuntsCount"))) { #optional property not found
            $AffectedTrackedHuntsCount = $null
        } else {
            $AffectedTrackedHuntsCount = $JsonParameters.PSobject.Properties["affectedTrackedHuntsCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "affectedOpenFindingsCount"))) { #optional property not found
            $AffectedOpenFindingsCount = $null
        } else {
            $AffectedOpenFindingsCount = $JsonParameters.PSobject.Properties["affectedOpenFindingsCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "affectedKbEntryIds"))) { #optional property not found
            $AffectedKbEntryIds = $null
        } else {
            $AffectedKbEntryIds = $JsonParameters.PSobject.Properties["affectedKbEntryIds"].value
        }

        $PSO = [PSCustomObject]@{
            "attackerId" = ${AttackerId}
            "name" = ${Name}
            "aliases" = ${Aliases}
            "type" = ${Type}
            "originCountryCode" = ${OriginCountryCode}
            "lastReportedDate" = ${LastReportedDate}
            "victimCountries" = ${VictimCountries}
            "targetIndustries" = ${TargetIndustries}
            "affectedTrackedHuntsCount" = ${AffectedTrackedHuntsCount}
            "affectedOpenFindingsCount" = ${AffectedOpenFindingsCount}
            "isAffected" = ${IsAffected}
            "affectedKbEntryIds" = ${AffectedKbEntryIds}
        }

        return $PSO
    }

}

