#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER AttackerId
No description available.
.PARAMETER Name
No description available.
.PARAMETER Type
No description available.
.PARAMETER Description
No description available.
.PARAMETER Aliases
No description available.
.PARAMETER CountryCode
No description available.
.PARAMETER FirstReportedDate
No description available.
.PARAMETER VulnerabilityLastUpdated
No description available.
.PARAMETER MitreLastUpdated
No description available.
.PARAMETER VictimCountries
No description available.
.PARAMETER TargetIndustries
No description available.
.PARAMETER LatestMedia
No description available.
.PARAMETER IsAffected
Whether the user has confirmed open findings against vulnerabilities exploited by this adversary. Scoped to the requesting user's business units and the organization's finding impact threshold.
.PARAMETER AffectedKbEntryIds
KB entry IDs that drive the `isAffected` flag, scoped to the requesting user's business units.
.OUTPUTS

AdversaryIntelDetails<PSCustomObject>
#>

function Initialize-AdversaryIntelDetails {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${AttackerId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Aliases},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CountryCode},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${FirstReportedDate},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${VulnerabilityLastUpdated},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${MitreLastUpdated},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VictimCountries},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${TargetIndustries},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${LatestMedia},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${IsAffected},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [Decimal[]]
        ${AffectedKbEntryIds}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => AdversaryIntelDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $AttackerId) {
            throw "invalid value for 'AttackerId', 'AttackerId' cannot be null."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $IsAffected) {
            throw "invalid value for 'IsAffected', 'IsAffected' cannot be null."
        }

        if ($null -eq $AffectedKbEntryIds) {
            throw "invalid value for 'AffectedKbEntryIds', 'AffectedKbEntryIds' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "attackerId" = ${AttackerId}
            "name" = ${Name}
            "type" = ${Type}
            "description" = ${Description}
            "aliases" = ${Aliases}
            "countryCode" = ${CountryCode}
            "firstReportedDate" = ${FirstReportedDate}
            "vulnerabilityLastUpdated" = ${VulnerabilityLastUpdated}
            "mitreLastUpdated" = ${MitreLastUpdated}
            "victimCountries" = ${VictimCountries}
            "targetIndustries" = ${TargetIndustries}
            "latestMedia" = ${LatestMedia}
            "isAffected" = ${IsAffected}
            "affectedKbEntryIds" = ${AffectedKbEntryIds}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AdversaryIntelDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to AdversaryIntelDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AdversaryIntelDetails<PSCustomObject>
#>
function ConvertFrom-JsonToAdversaryIntelDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => AdversaryIntelDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AdversaryIntelDetails
        $AllProperties = ("attackerId", "name", "type", "description", "aliases", "countryCode", "firstReportedDate", "vulnerabilityLastUpdated", "mitreLastUpdated", "victimCountries", "targetIndustries", "latestMedia", "isAffected", "affectedKbEntryIds")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'attackerId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "attackerId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'attackerId' missing."
        } else {
            $AttackerId = $JsonParameters.PSobject.Properties["attackerId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isAffected"))) {
            throw "Error! JSON cannot be serialized due to the required property 'isAffected' missing."
        } else {
            $IsAffected = $JsonParameters.PSobject.Properties["isAffected"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "affectedKbEntryIds"))) {
            throw "Error! JSON cannot be serialized due to the required property 'affectedKbEntryIds' missing."
        } else {
            $AffectedKbEntryIds = $JsonParameters.PSobject.Properties["affectedKbEntryIds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "aliases"))) { #optional property not found
            $Aliases = $null
        } else {
            $Aliases = $JsonParameters.PSobject.Properties["aliases"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "countryCode"))) { #optional property not found
            $CountryCode = $null
        } else {
            $CountryCode = $JsonParameters.PSobject.Properties["countryCode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "firstReportedDate"))) { #optional property not found
            $FirstReportedDate = $null
        } else {
            $FirstReportedDate = $JsonParameters.PSobject.Properties["firstReportedDate"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vulnerabilityLastUpdated"))) { #optional property not found
            $VulnerabilityLastUpdated = $null
        } else {
            $VulnerabilityLastUpdated = $JsonParameters.PSobject.Properties["vulnerabilityLastUpdated"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mitreLastUpdated"))) { #optional property not found
            $MitreLastUpdated = $null
        } else {
            $MitreLastUpdated = $JsonParameters.PSobject.Properties["mitreLastUpdated"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "victimCountries"))) { #optional property not found
            $VictimCountries = $null
        } else {
            $VictimCountries = $JsonParameters.PSobject.Properties["victimCountries"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "targetIndustries"))) { #optional property not found
            $TargetIndustries = $null
        } else {
            $TargetIndustries = $JsonParameters.PSobject.Properties["targetIndustries"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "latestMedia"))) { #optional property not found
            $LatestMedia = $null
        } else {
            $LatestMedia = $JsonParameters.PSobject.Properties["latestMedia"].value
        }

        $PSO = [PSCustomObject]@{
            "attackerId" = ${AttackerId}
            "name" = ${Name}
            "type" = ${Type}
            "description" = ${Description}
            "aliases" = ${Aliases}
            "countryCode" = ${CountryCode}
            "firstReportedDate" = ${FirstReportedDate}
            "vulnerabilityLastUpdated" = ${VulnerabilityLastUpdated}
            "mitreLastUpdated" = ${MitreLastUpdated}
            "victimCountries" = ${VictimCountries}
            "targetIndustries" = ${TargetIndustries}
            "latestMedia" = ${LatestMedia}
            "isAffected" = ${IsAffected}
            "affectedKbEntryIds" = ${AffectedKbEntryIds}
        }

        return $PSO
    }

}

