#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER AptGroup
No description available.
.PARAMETER Ransomware
No description available.
.PARAMETER Botnet
No description available.
.OUTPUTS

AttackerTypes<PSCustomObject>
#>

function Initialize-AttackerTypes {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${AptGroup},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Ransomware},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Botnet}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => AttackerTypes' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $AptGroup) {
            throw "invalid value for 'AptGroup', 'AptGroup' cannot be null."
        }

        if ($null -eq $Ransomware) {
            throw "invalid value for 'Ransomware', 'Ransomware' cannot be null."
        }

        if ($null -eq $Botnet) {
            throw "invalid value for 'Botnet', 'Botnet' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "aptGroup" = ${AptGroup}
            "ransomware" = ${Ransomware}
            "botnet" = ${Botnet}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AttackerTypes<PSCustomObject>

.DESCRIPTION

Convert from JSON to AttackerTypes<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AttackerTypes<PSCustomObject>
#>
function ConvertFrom-JsonToAttackerTypes {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => AttackerTypes' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AttackerTypes
        $AllProperties = ("aptGroup", "ransomware", "botnet")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'aptGroup' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "aptGroup"))) {
            throw "Error! JSON cannot be serialized due to the required property 'aptGroup' missing."
        } else {
            $AptGroup = $JsonParameters.PSobject.Properties["aptGroup"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ransomware"))) {
            throw "Error! JSON cannot be serialized due to the required property 'ransomware' missing."
        } else {
            $Ransomware = $JsonParameters.PSobject.Properties["ransomware"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "botnet"))) {
            throw "Error! JSON cannot be serialized due to the required property 'botnet' missing."
        } else {
            $Botnet = $JsonParameters.PSobject.Properties["botnet"].value
        }

        $PSO = [PSCustomObject]@{
            "aptGroup" = ${AptGroup}
            "ransomware" = ${Ransomware}
            "botnet" = ${Botnet}
        }

        return $PSO
    }

}

