#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER VarData
No description available.
.PARAMETER DnsConnectedRetestsTriggered
Number of additional DNS-connected findings retested alongside the requested finding (present when `includeDnsConnected=true`).
.OUTPUTS

ClientFindingRetestResponse<PSCustomObject>
#>

function Initialize-ClientFindingRetestResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VarData},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${DnsConnectedRetestsTriggered}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => ClientFindingRetestResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $VarData) {
            throw "invalid value for 'VarData', 'VarData' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "data" = ${VarData}
            "dnsConnectedRetestsTriggered" = ${DnsConnectedRetestsTriggered}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClientFindingRetestResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClientFindingRetestResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClientFindingRetestResponse<PSCustomObject>
#>
function ConvertFrom-JsonToClientFindingRetestResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => ClientFindingRetestResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClientFindingRetestResponse
        $AllProperties = ("data", "dnsConnectedRetestsTriggered")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'data' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data"))) {
            throw "Error! JSON cannot be serialized due to the required property 'data' missing."
        } else {
            $VarData = $JsonParameters.PSobject.Properties["data"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dnsConnectedRetestsTriggered"))) { #optional property not found
            $DnsConnectedRetestsTriggered = $null
        } else {
            $DnsConnectedRetestsTriggered = $JsonParameters.PSobject.Properties["dnsConnectedRetestsTriggered"].value
        }

        $PSO = [PSCustomObject]@{
            "data" = ${VarData}
            "dnsConnectedRetestsTriggered" = ${DnsConnectedRetestsTriggered}
        }

        return $PSO
    }

}

