#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Username
Username used in the credential attempt
.PARAMETER TargetUrl
Target URL for the credential attempt
.OUTPUTS

ClientCredentialsLogCredentials<PSCustomObject>
#>

function Initialize-ClientCredentialsLogCredentials {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Username},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TargetUrl}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => ClientCredentialsLogCredentials' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $TargetUrl) {
            throw "invalid value for 'TargetUrl', 'TargetUrl' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "username" = ${Username}
            "targetUrl" = ${TargetUrl}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClientCredentialsLogCredentials<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClientCredentialsLogCredentials<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClientCredentialsLogCredentials<PSCustomObject>
#>
function ConvertFrom-JsonToClientCredentialsLogCredentials {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => ClientCredentialsLogCredentials' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ClientCredentialsLogCredentials
        $AllProperties = ("username", "targetUrl")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'username' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "username"))) {
            throw "Error! JSON cannot be serialized due to the required property 'username' missing."
        } else {
            $Username = $JsonParameters.PSobject.Properties["username"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "targetUrl"))) {
            throw "Error! JSON cannot be serialized due to the required property 'targetUrl' missing."
        } else {
            $TargetUrl = $JsonParameters.PSobject.Properties["targetUrl"].value
        }

        $PSO = [PSCustomObject]@{
            "username" = ${Username}
            "targetUrl" = ${TargetUrl}
        }

        return $PSO
    }

}

