#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER BoardName
Name of the external board or ticketing system.
.PARAMETER IssueLink
URL of the manually created ticket.
.OUTPUTS

CreateClientFindingManualTicketRequestBody<PSCustomObject>
#>

function Initialize-CreateClientFindingManualTicketRequestBody {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BoardName},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IssueLink}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => CreateClientFindingManualTicketRequestBody' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $BoardName) {
            throw "invalid value for 'BoardName', 'BoardName' cannot be null."
        }

        if ($null -eq $IssueLink) {
            throw "invalid value for 'IssueLink', 'IssueLink' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "boardName" = ${BoardName}
            "issueLink" = ${IssueLink}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CreateClientFindingManualTicketRequestBody<PSCustomObject>

.DESCRIPTION

Convert from JSON to CreateClientFindingManualTicketRequestBody<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CreateClientFindingManualTicketRequestBody<PSCustomObject>
#>
function ConvertFrom-JsonToCreateClientFindingManualTicketRequestBody {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => CreateClientFindingManualTicketRequestBody' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CreateClientFindingManualTicketRequestBody
        $AllProperties = ("boardName", "issueLink")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'boardName' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "boardName"))) {
            throw "Error! JSON cannot be serialized due to the required property 'boardName' missing."
        } else {
            $BoardName = $JsonParameters.PSobject.Properties["boardName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "issueLink"))) {
            throw "Error! JSON cannot be serialized due to the required property 'issueLink' missing."
        } else {
            $IssueLink = $JsonParameters.PSobject.Properties["issueLink"].value
        }

        $PSO = [PSCustomObject]@{
            "boardName" = ${BoardName}
            "issueLink" = ${IssueLink}
        }

        return $PSO
    }

}

