#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Success
Success status
.PARAMETER InvitedCount
Number of users invited
.PARAMETER InvitedEmails
List of emails that were invited
.OUTPUTS

InviteUserResponse<PSCustomObject>
#>

function Initialize-InviteUserResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Success},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${InvitedCount},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${InvitedEmails}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => InviteUserResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Success) {
            throw "invalid value for 'Success', 'Success' cannot be null."
        }

        if ($null -eq $InvitedCount) {
            throw "invalid value for 'InvitedCount', 'InvitedCount' cannot be null."
        }

        if ($null -eq $InvitedEmails) {
            throw "invalid value for 'InvitedEmails', 'InvitedEmails' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "success" = ${Success}
            "invitedCount" = ${InvitedCount}
            "invitedEmails" = ${InvitedEmails}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to InviteUserResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to InviteUserResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

InviteUserResponse<PSCustomObject>
#>
function ConvertFrom-JsonToInviteUserResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => InviteUserResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in InviteUserResponse
        $AllProperties = ("success", "invitedCount", "invitedEmails")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'success' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "success"))) {
            throw "Error! JSON cannot be serialized due to the required property 'success' missing."
        } else {
            $Success = $JsonParameters.PSobject.Properties["success"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "invitedCount"))) {
            throw "Error! JSON cannot be serialized due to the required property 'invitedCount' missing."
        } else {
            $InvitedCount = $JsonParameters.PSobject.Properties["invitedCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "invitedEmails"))) {
            throw "Error! JSON cannot be serialized due to the required property 'invitedEmails' missing."
        } else {
            $InvitedEmails = $JsonParameters.PSobject.Properties["invitedEmails"].value
        }

        $PSO = [PSCustomObject]@{
            "success" = ${Success}
            "invitedCount" = ${InvitedCount}
            "invitedEmails" = ${InvitedEmails}
        }

        return $PSO
    }

}

