#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
The unique identifier for the WHOIS record.
.PARAMETER VarData
No description available.
.PARAMETER Raw
The full WHOIS text of the record.
.OUTPUTS

IpWhoisData<PSCustomObject>
#>

function Initialize-IpWhoisData {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VarData},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Raw}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => IpWhoisData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($null -eq $VarData) {
            throw "invalid value for 'VarData', 'VarData' cannot be null."
        }

        if ($null -eq $Raw) {
            throw "invalid value for 'Raw', 'Raw' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "data" = ${VarData}
            "raw" = ${Raw}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to IpWhoisData<PSCustomObject>

.DESCRIPTION

Convert from JSON to IpWhoisData<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

IpWhoisData<PSCustomObject>
#>
function ConvertFrom-JsonToIpWhoisData {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => IpWhoisData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in IpWhoisData
        $AllProperties = ("id", "data", "raw")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data"))) {
            throw "Error! JSON cannot be serialized due to the required property 'data' missing."
        } else {
            $VarData = $JsonParameters.PSobject.Properties["data"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "raw"))) {
            throw "Error! JSON cannot be serialized due to the required property 'raw' missing."
        } else {
            $Raw = $JsonParameters.PSobject.Properties["raw"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "data" = ${VarData}
            "raw" = ${Raw}
        }

        return $PSO
    }

}

