#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Url
No description available.
.PARAMETER Title
No description available.
.PARAMETER PublishedAt
No description available.
.OUTPUTS

Media<PSCustomObject>
#>

function Initialize-Media {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Url},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${PublishedAt}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => Media' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "url" = ${Url}
            "title" = ${Title}
            "publishedAt" = ${PublishedAt}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Media<PSCustomObject>

.DESCRIPTION

Convert from JSON to Media<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Media<PSCustomObject>
#>
function ConvertFrom-JsonToMedia {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => Media' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Media
        $AllProperties = ("url", "title", "publishedAt")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "url"))) { #optional property not found
            $Url = $null
        } else {
            $Url = $JsonParameters.PSobject.Properties["url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "publishedAt"))) { #optional property not found
            $PublishedAt = $null
        } else {
            $PublishedAt = $JsonParameters.PSobject.Properties["publishedAt"].value
        }

        $PSO = [PSCustomObject]@{
            "url" = ${Url}
            "title" = ${Title}
            "publishedAt" = ${PublishedAt}
        }

        return $PSO
    }

}

