#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ActivelyExploitedFindings
Count of open findings currently being actively exploited
.PARAMETER UnresolvedRapidReactionHunts
Count of unresolved rapid reaction hunts
.OUTPUTS

RequiredActionsDto<PSCustomObject>
#>

function Initialize-RequiredActionsDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${ActivelyExploitedFindings},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${UnresolvedRapidReactionHunts}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => RequiredActionsDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ActivelyExploitedFindings) {
            throw "invalid value for 'ActivelyExploitedFindings', 'ActivelyExploitedFindings' cannot be null."
        }

        if ($null -eq $UnresolvedRapidReactionHunts) {
            throw "invalid value for 'UnresolvedRapidReactionHunts', 'UnresolvedRapidReactionHunts' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "activelyExploitedFindings" = ${ActivelyExploitedFindings}
            "unresolvedRapidReactionHunts" = ${UnresolvedRapidReactionHunts}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to RequiredActionsDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to RequiredActionsDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

RequiredActionsDto<PSCustomObject>
#>
function ConvertFrom-JsonToRequiredActionsDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => RequiredActionsDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RequiredActionsDto
        $AllProperties = ("activelyExploitedFindings", "unresolvedRapidReactionHunts")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'activelyExploitedFindings' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "activelyExploitedFindings"))) {
            throw "Error! JSON cannot be serialized due to the required property 'activelyExploitedFindings' missing."
        } else {
            $ActivelyExploitedFindings = $JsonParameters.PSobject.Properties["activelyExploitedFindings"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "unresolvedRapidReactionHunts"))) {
            throw "Error! JSON cannot be serialized due to the required property 'unresolvedRapidReactionHunts' missing."
        } else {
            $UnresolvedRapidReactionHunts = $JsonParameters.PSobject.Properties["unresolvedRapidReactionHunts"].value
        }

        $PSO = [PSCustomObject]@{
            "activelyExploitedFindings" = ${ActivelyExploitedFindings}
            "unresolvedRapidReactionHunts" = ${UnresolvedRapidReactionHunts}
        }

        return $PSO
    }

}

