#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Criticality
The criticality level to assign to the asset. Accepted values are 'High', 'Medium', 'Low', 'Unknown'.
.OUTPUTS

SetCriticalityDto<PSCustomObject>
#>

function Initialize-SetCriticalityDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("High", "Medium", "Low", "Unknown")]
        [String]
        ${Criticality}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => SetCriticalityDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Criticality) {
            throw "invalid value for 'Criticality', 'Criticality' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "criticality" = ${Criticality}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SetCriticalityDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to SetCriticalityDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SetCriticalityDto<PSCustomObject>
#>
function ConvertFrom-JsonToSetCriticalityDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => SetCriticalityDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SetCriticalityDto
        $AllProperties = ("criticality")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'criticality' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "criticality"))) {
            throw "Error! JSON cannot be serialized due to the required property 'criticality' missing."
        } else {
            $Criticality = $JsonParameters.PSobject.Properties["criticality"].value
        }

        $PSO = [PSCustomObject]@{
            "criticality" = ${Criticality}
        }

        return $PSO
    }

}

