#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Message
No description available.
.PARAMETER StatusCode
No description available.
.PARAMETER Errors
No description available.
.OUTPUTS

UnprocessableContent<PSCustomObject>
#>

function Initialize-UnprocessableContent {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Message},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${StatusCode},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Errors}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => UnprocessableContent' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Message) {
            throw "invalid value for 'Message', 'Message' cannot be null."
        }

        if ($null -eq $StatusCode) {
            throw "invalid value for 'StatusCode', 'StatusCode' cannot be null."
        }

        if ($null -eq $Errors) {
            throw "invalid value for 'Errors', 'Errors' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "message" = ${Message}
            "status_code" = ${StatusCode}
            "errors" = ${Errors}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to UnprocessableContent<PSCustomObject>

.DESCRIPTION

Convert from JSON to UnprocessableContent<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

UnprocessableContent<PSCustomObject>
#>
function ConvertFrom-JsonToUnprocessableContent {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => UnprocessableContent' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in UnprocessableContent
        $AllProperties = ("message", "status_code", "errors")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'message' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "message"))) {
            throw "Error! JSON cannot be serialized due to the required property 'message' missing."
        } else {
            $Message = $JsonParameters.PSobject.Properties["message"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "status_code"))) {
            throw "Error! JSON cannot be serialized due to the required property 'status_code' missing."
        } else {
            $StatusCode = $JsonParameters.PSobject.Properties["status_code"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "errors"))) {
            throw "Error! JSON cannot be serialized due to the required property 'errors' missing."
        } else {
            $Errors = $JsonParameters.PSobject.Properties["errors"].value
        }

        $PSO = [PSCustomObject]@{
            "message" = ${Message}
            "status_code" = ${StatusCode}
            "errors" = ${Errors}
        }

        return $PSO
    }

}

