#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Score
No description available.
.PARAMETER Percentile
No description available.
.PARAMETER EpssScoreLevel
No description available.
.OUTPUTS

VulnEpss<PSCustomObject>
#>

function Initialize-VulnEpss {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Score},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Percentile},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EpssScoreLevel}
    )

    Process {
        'Creating PSCustomObject: WatchtowrAPI => VulnEpss' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "score" = ${Score}
            "percentile" = ${Percentile}
            "epssScoreLevel" = ${EpssScoreLevel}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VulnEpss<PSCustomObject>

.DESCRIPTION

Convert from JSON to VulnEpss<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VulnEpss<PSCustomObject>
#>
function ConvertFrom-JsonToVulnEpss {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: WatchtowrAPI => VulnEpss' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in VulnEpss
        $AllProperties = ("score", "percentile", "epssScoreLevel")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "score"))) { #optional property not found
            $Score = $null
        } else {
            $Score = $JsonParameters.PSobject.Properties["score"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "percentile"))) { #optional property not found
            $Percentile = $null
        } else {
            $Percentile = $JsonParameters.PSobject.Properties["percentile"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "epssScoreLevel"))) { #optional property not found
            $EpssScoreLevel = $null
        } else {
            $EpssScoreLevel = $JsonParameters.PSobject.Properties["epssScoreLevel"].value
        }

        $PSO = [PSCustomObject]@{
            "score" = ${Score}
            "percentile" = ${Percentile}
            "epssScoreLevel" = ${EpssScoreLevel}
        }

        return $PSO
    }

}

