#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Mttr
Mean Time To Remediation in hours
.PARAMETER Mttrae
Mean Time To Remediation After Exploitation in hours
.OUTPUTS

MttrMetricsDto<PSCustomObject>
#>

function Initialize-MttrMetricsDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${Mttr},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${Mttrae}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => MttrMetricsDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Mttr) {
            throw "invalid value for 'Mttr', 'Mttr' cannot be null."
        }

        if ($null -eq $Mttrae) {
            throw "invalid value for 'Mttrae', 'Mttrae' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "mttr" = ${Mttr}
            "mttrae" = ${Mttrae}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to MttrMetricsDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to MttrMetricsDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

MttrMetricsDto<PSCustomObject>
#>
function ConvertFrom-JsonToMttrMetricsDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => MttrMetricsDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in MttrMetricsDto
        $AllProperties = ("mttr", "mttrae")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'mttr' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mttr"))) {
            throw "Error! JSON cannot be serialized due to the required property 'mttr' missing."
        } else {
            $Mttr = $JsonParameters.PSobject.Properties["mttr"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mttrae"))) {
            throw "Error! JSON cannot be serialized due to the required property 'mttrae' missing."
        } else {
            $Mttrae = $JsonParameters.PSobject.Properties["mttrae"].value
        }

        $PSO = [PSCustomObject]@{
            "mttr" = ${Mttr}
            "mttrae" = ${Mttrae}
        }

        return $PSO
    }

}

