#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'HuntsApi' {
    Context 'Get-ClientHunts' {
        It 'Test Get-ClientHunts' {
            #$TestResult = Get-ClientHunts -Page "TEST_VALUE" -PageSize "TEST_VALUE" -Statuses "TEST_VALUE" -HuntSearch "TEST_VALUE" -Types "TEST_VALUE" -CreatedFrom "TEST_VALUE" -CreatedTo "TEST_VALUE" -UpdatedFrom "TEST_VALUE" -UpdatedTo "TEST_VALUE" -Priorities "TEST_VALUE" -ResourceFilter "TEST_VALUE" -OnlyResolved "TEST_VALUE" -IsUnacknowledged "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ListAssetByHunt' {
        It 'Test Get-ListAssetByHunt' {
            #$TestResult = Get-ListAssetByHunt -Id "TEST_VALUE" -Page "TEST_VALUE" -PageSize "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ListFindingByHunt' {
        It 'Test Get-ListFindingByHunt' {
            #$TestResult = Get-ListFindingByHunt -Id "TEST_VALUE" -Page "TEST_VALUE" -PageSize "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Show-TheDetailHunt' {
        It 'Test Show-TheDetailHunt' {
            #$TestResult = Show-TheDetailHunt -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
