#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'AdversaryIntelDetails' {
    Context 'AdversaryIntelDetails' {
        It 'Initialize-AdversaryIntelDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-AdversaryIntelDetails -AttackerId "TEST_VALUE" -Name "TEST_VALUE" -Type "TEST_VALUE" -Description "TEST_VALUE" -Aliases "TEST_VALUE" -CountryCode "TEST_VALUE" -FirstReportedDate "TEST_VALUE" -VulnerabilityLastUpdated "TEST_VALUE" -MitreLastUpdated "TEST_VALUE" -VictimCountries "TEST_VALUE" -TargetIndustries "TEST_VALUE" -LatestMedia "TEST_VALUE" -IsAffected "TEST_VALUE" -AffectedKbEntryIds "TEST_VALUE"
            #$NewObject | Should -BeOfType AdversaryIntelDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
