#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'AttackerTypes' {
    Context 'AttackerTypes' {
        It 'Initialize-AttackerTypes' {
            # a simple test to create an object
            #$NewObject = Initialize-AttackerTypes -AptGroup "TEST_VALUE" -Ransomware "TEST_VALUE" -Botnet "TEST_VALUE"
            #$NewObject | Should -BeOfType AttackerTypes
            #$NewObject.property | Should -Be 0
        }
    }
}
