#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'ClientEngineSettings' {
    Context 'ClientEngineSettings' {
        It 'Initialize-ClientEngineSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-ClientEngineSettings -AdversarySightEnabled "TEST_VALUE" -AutomatedRedTeamingEnabled "TEST_VALUE" -CredentialStuffingEnabled "TEST_VALUE" -DnsBruteforcingEnabled "TEST_VALUE" -RapidReactionEnabled "TEST_VALUE" -IntrusiveHttpChecksEnabled "TEST_VALUE"
            #$NewObject | Should -BeOfType ClientEngineSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
