#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'ClientActivityLog' {
    Context 'ClientActivityLog' {
        It 'Initialize-ClientActivityLog' {
            # a simple test to create an object
            #$NewObject = Initialize-ClientActivityLog -Id "TEST_VALUE" -Description "TEST_VALUE" -Type "TEST_VALUE" -Properties "TEST_VALUE" -CreatedAt "TEST_VALUE" -CausedBy "TEST_VALUE"
            #$NewObject | Should -BeOfType ClientActivityLog
            #$NewObject.property | Should -Be 0
        }
    }
}
