#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'ClientPackageManagerData' {
    Context 'ClientPackageManagerData' {
        It 'Initialize-ClientPackageManagerData' {
            # a simple test to create an object
            #$NewObject = Initialize-ClientPackageManagerData -VarData "TEST_VALUE"
            #$NewObject | Should -BeOfType ClientPackageManagerData
            #$NewObject.property | Should -Be 0
        }
    }
}
