#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'ClientUserDetail' {
    Context 'ClientUserDetail' {
        It 'Initialize-ClientUserDetail' {
            # a simple test to create an object
            #$NewObject = Initialize-ClientUserDetail -Id "TEST_VALUE" -Name "TEST_VALUE" -Email "TEST_VALUE" -Title "TEST_VALUE" -MobilePhoneNumber "TEST_VALUE" -OfficePhoneNumber "TEST_VALUE" -CreatedAt "TEST_VALUE" -Locked "TEST_VALUE" -Role "TEST_VALUE"
            #$NewObject | Should -BeOfType ClientUserDetail
            #$NewObject.property | Should -Be 0
        }
    }
}
