#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'ClientPort' {
    Context 'ClientPort' {
        It 'Initialize-ClientPort' {
            # a simple test to create an object
            #$NewObject = Initialize-ClientPort -Type "TEST_VALUE" -Status "TEST_VALUE" -CreatedAt "TEST_VALUE" -UpdatedAt "TEST_VALUE" -LastSeenAt "TEST_VALUE" -DeletedAt "TEST_VALUE" -Id "TEST_VALUE" -Ip "TEST_VALUE" -IpId "TEST_VALUE" -Port "TEST_VALUE" -Banner "TEST_VALUE" -Service "TEST_VALUE" -BusinessUnits "TEST_VALUE"
            #$NewObject | Should -BeOfType ClientPort
            #$NewObject.property | Should -Be 0
        }
    }
}
