#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CreateClientSeedDataRequestBody' {
    Context 'CreateClientSeedDataRequestBody' {
        It 'Initialize-CreateClientSeedDataRequestBody' {
            # a simple test to create an object
            #$NewObject = Initialize-CreateClientSeedDataRequestBody -VarData "TEST_VALUE" -BusinessUnits "TEST_VALUE"
            #$NewObject | Should -BeOfType CreateClientSeedDataRequestBody
            #$NewObject.property | Should -Be 0
        }
    }
}
