#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'DeleteWhitelistIpData' {
    Context 'DeleteWhitelistIpData' {
        It 'Initialize-DeleteWhitelistIpData' {
            # a simple test to create an object
            #$NewObject = Initialize-DeleteWhitelistIpData -Id "TEST_VALUE"
            #$NewObject | Should -BeOfType DeleteWhitelistIpData
            #$NewObject.property | Should -Be 0
        }
    }
}
