#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'FindingRetestResponseDto' {
    Context 'FindingRetestResponseDto' {
        It 'Initialize-FindingRetestResponseDto' {
            # a simple test to create an object
            #$NewObject = Initialize-FindingRetestResponseDto -RequestedBy "TEST_VALUE" -RequestedAt "TEST_VALUE" -RetestStatus "TEST_VALUE" -StatusOccurredAt "TEST_VALUE" -CompletedAt "TEST_VALUE" -Evidence "TEST_VALUE"
            #$NewObject | Should -BeOfType FindingRetestResponseDto
            #$NewObject.property | Should -Be 0
        }
    }
}
