#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'GetAssetRepositoryChangelog200Response' {
    Context 'GetAssetRepositoryChangelog200Response' {
        It 'Initialize-GetAssetRepositoryChangelog200Response' {
            # a simple test to create an object
            #$NewObject = Initialize-GetAssetRepositoryChangelog200Response -VarData "TEST_VALUE" -Meta "TEST_VALUE"
            #$NewObject | Should -BeOfType GetAssetRepositoryChangelog200Response
            #$NewObject.property | Should -Be 0
        }
    }
}
