#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'Hunt' {
    Context 'Hunt' {
        It 'Initialize-Hunt' {
            # a simple test to create an object
            #$NewObject = Initialize-Hunt -Id "TEST_VALUE" -Priority "TEST_VALUE" -Type "TEST_VALUE" -CreatedAt "TEST_VALUE" -UpdatedAt "TEST_VALUE" -TotalFindings "TEST_VALUE" -TotalAssets "TEST_VALUE" -HuntRequestType "TEST_VALUE" -RapidExposureMechanism "TEST_VALUE" -Title "TEST_VALUE" -Status "TEST_VALUE"
            #$NewObject | Should -BeOfType Hunt
            #$NewObject.property | Should -Be 0
        }
    }
}
