#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'Infrastructure' {
    Context 'Infrastructure' {
        It 'Initialize-Infrastructure' {
            # a simple test to create an object
            #$NewObject = Initialize-Infrastructure -CDN "TEST_VALUE" -Cloud "TEST_VALUE" -WAF "TEST_VALUE"
            #$NewObject | Should -BeOfType Infrastructure
            #$NewObject.property | Should -Be 0
        }
    }
}
