#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'InviteUserResponse' {
    Context 'InviteUserResponse' {
        It 'Initialize-InviteUserResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-InviteUserResponse -Success "TEST_VALUE" -InvitedCount "TEST_VALUE" -InvitedEmails "TEST_VALUE"
            #$NewObject | Should -BeOfType InviteUserResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
