#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'IpWhoisDataObject' {
    Context 'IpWhoisDataObject' {
        It 'Initialize-IpWhoisDataObject' {
            # a simple test to create an object
            #$NewObject = Initialize-IpWhoisDataObject -Asn "TEST_VALUE" -AsnCidr "TEST_VALUE" -AsnCountryCode "TEST_VALUE" -AsnDate "TEST_VALUE" -AsnDescription "TEST_VALUE" -AsnRegistry "TEST_VALUE" -Query "TEST_VALUE" -Nets "TEST_VALUE" -Nir "TEST_VALUE" -Referral "TEST_VALUE" -RawReferral "TEST_VALUE" -Message "TEST_VALUE"
            #$NewObject | Should -BeOfType IpWhoisDataObject
            #$NewObject.property | Should -Be 0
        }
    }
}
