#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'ServiceInformationCertificate' {
    Context 'ServiceInformationCertificate' {
        It 'Initialize-ServiceInformationCertificate' {
            # a simple test to create an object
            #$NewObject = Initialize-ServiceInformationCertificate -Id "TEST_VALUE" -SubjectCommonName "TEST_VALUE" -SubjectOrganisation "TEST_VALUE" -SubjectAltNames "TEST_VALUE" -SubjectCountry "TEST_VALUE" -IssuerCommonName "TEST_VALUE" -IssuerOrganisation "TEST_VALUE" -IssuerCountry "TEST_VALUE" -Fingerprint "TEST_VALUE" -PublicKeyInfoAlg "TEST_VALUE" -PublicKeyInfoSize "TEST_VALUE" -Status "TEST_VALUE" -CreatedAt "TEST_VALUE"
            #$NewObject | Should -BeOfType ServiceInformationCertificate
            #$NewObject.property | Should -Be 0
        }
    }
}
