#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'SuspiciousDomain' {
    Context 'SuspiciousDomain' {
        It 'Initialize-SuspiciousDomain' {
            # a simple test to create an object
            #$NewObject = Initialize-SuspiciousDomain -Id "TEST_VALUE" -Name "TEST_VALUE" -DiscoveryReason "TEST_VALUE" -Status "TEST_VALUE" -WhoisData "TEST_VALUE" -CreatedAt "TEST_VALUE"
            #$NewObject | Should -BeOfType SuspiciousDomain
            #$NewObject.property | Should -Be 0
        }
    }
}
