#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'UpdateKillSwitchRequestDto' {
    Context 'UpdateKillSwitchRequestDto' {
        It 'Initialize-UpdateKillSwitchRequestDto' {
            # a simple test to create an object
            #$NewObject = Initialize-UpdateKillSwitchRequestDto -Value "TEST_VALUE" -Reason "TEST_VALUE" -RequestSupport "TEST_VALUE"
            #$NewObject | Should -BeOfType UpdateKillSwitchRequestDto
            #$NewObject.property | Should -Be 0
        }
    }
}
