#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'WatchtowrAPI' -name 'WhitelistIpData' {
    Context 'WhitelistIpData' {
        It 'Initialize-WhitelistIpData' {
            # a simple test to create an object
            #$NewObject = Initialize-WhitelistIpData -Id "TEST_VALUE" -Ip "TEST_VALUE" -Description "TEST_VALUE" -CreatedAt "TEST_VALUE" -UpdatedAt "TEST_VALUE"
            #$NewObject | Should -BeOfType WhitelistIpData
            #$NewObject.property | Should -Be 0
        }
    }
}
