#
# Complete watchTowr Platform API Documentation
# The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 
# Version: 1.0
# Contact: support@watchTowr.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WhoisData' {
    Context 'WhoisData' {
        It 'Initialize-WhoisData' {
            # a simple test to create an object
            #$NewObject = Initialize-WhoisData -Id "TEST_VALUE" -VarData "TEST_VALUE" -Raw "TEST_VALUE"
            #$NewObject | Should -BeOfType WhoisData
            #$NewObject.property | Should -Be 0
        }
    }
}
